<?php $blockData = $block->thisPageData();
if ($blockData) {
    $maskedId = $blockData['masked_id'];
}
?>
<?php if ($maskedId): ?>
    <div id="tp_pb_ctn" />
    <script type="text/javascript">
        require([
            "https://tapita.io/pb/pub/media/Simipbuilder/simi-pagebuilder-react@1.3.8.umd.js"
        ], function(PageBuilderComponent) {
            PageBuilderComponent.renderForIdWithProps('tp_pb_ctn', {
                endPoint: "https://tapita.io/pb/graphql/",
                maskedId: "<?php echo $maskedId ?>"
            })
        });
    </script>
<?php endif; ?>