<?php $params = $block->getRequest()->getParams();
$maskedId = false;
if ($params && isset($params['maskedid'])) {
    $maskedId = $params['maskedid'];
} else if ($params && isset($params['maskedId'])) {
    $maskedId = $params['maskedId'];
}

?>
<div id="pbwidget-id-preview" style="display: none">
    <?php echo $this->getLayout()->createBlock("Magento\CatalogWidget\Block\Product\ProductsList")
        ->setData('conditions_encoded', "^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^]^]")
        ->setDisplayType("all_products")->setProductsCount("5")->setTemplate("product/widget/content/grid.phtml")->toHtml(); ?>
</div>
<?php if ($maskedId) : ?>
    <div id="tp_pb_ctn" />
    <script type="text/javascript">
        require([
            "https://tapita.io/pb/pub/media/Simipbuilder/simi-pagebuilder-react@1.3.8.umd.js"
        ], function(PageBuilderComponent) {
            PageBuilderComponent.renderForIdWithProps('tp_pb_ctn', {
                endPoint: "https://tapita.io/pb/graphql/",
                maskedId: "<?php echo $maskedId ?>",
                toPreview: true,
            })
        });
    </script>
    <script type="text/javascript">
        function applyPbpreviewContent() {
            var sourceEl = document.getElementById("pbwidget-id-preview");
            var pbEls = document.querySelectorAll(".product_grid, .type_product_scroll, .product_scroll_1");
            if (pbEls && pbEls.length) {
                pbEls.forEach(pbEl => {
                    pbEl.style.display = "block";
                    pbEl.innerHTML = sourceEl.innerHTML;
                });
            }
        }
        setTimeout(function() {
            window.addEventListener("resize", function(event) {
                applyPbpreviewContent();
            }, true);

            var pbEls = document.querySelectorAll(".product_grid, .type_product_scroll, .product_scroll_1");
            if (pbEls && pbEls.length)
                applyPbpreviewContent();
            else
                setTimeout(function() {
                    applyPbpreviewContent();
                }, 2000);
        }, 300);
    </script>
<?php endif; ?>