<?php $params = $block->getRequest()->getParams();
$maskedId = false;
if ($params && isset($params['maskedid'])) {
    $maskedId = $params['maskedid'];
} else if ($params && isset($params['maskedId'])) {
    $maskedId = $params['maskedId'];
}
?>
<?php echo $block->getPreloadPreviewWidgets(); ?>
<?php if ($maskedId) : ?>
    <div id="tp_pb_ctn" />
    <script type="text/javascript">
        require([
            "Tapita_Tpbuilder/js/simi-pagebuilder-react@1.4.0.umd"
        ], function(PageBuilderComponent) {
            PageBuilderComponent.renderForIdWithProps('tp_pb_ctn', {
                endPoint: "https://tapita.io/pb/graphql/",
                maskedId: "<?php echo $maskedId ?>",
                toPreview: true,
            })
        });
    </script>
<?php endif; ?>